cargo-features = ["edition2021"]

[package]
name = "common-datavalues"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-exception = {path = "../exception"}
common-io = {path = "../io"}

# Github dependencies

# Crates.io dependencies
num = "^0.4"
ordered-float = "2.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ahash = "0.7.4"
comfy-table = "4.1.1"
strength_reduce = "0.2.3"
lexical-core = "0.7.6"
chrono = "0.4.0"
chrono-tz = "0.5"


[dev-dependencies]
pretty_assertions = "0.7"
