[package]
name = "databend-common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
anyhow = { workspace = true }
backtrace = { workspace = true, features = ["std", "serialize-serde"] }
chrono = { workspace = true }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
defer = "0.2"
fastrace = { workspace = true }
fastrace-opentelemetry = { workspace = true }
itertools = { workspace = true }
libc = "0.2.153"
log = { workspace = true }
logforth = { version = "0.12", features = [
    'json',
    'rolling_file',
    'opentelemetry',
    'fastrace',
] }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
tonic = { workspace = true }
bytes = "1.5.0"

[dev-dependencies]

[lints]
workspace = true
